[req]
distinguished_name = req_distinguished_name
prompt = no
x509_extensions = v3_req

[req_distinguished_name]
C  = PE
ST = Lima
L  = Lima
O  = EMPRESA DEMO SAC
OU = Facturacion Electronica
CN = 20000000001
emailAddress = demo@demo.pe

[v3_req]
basicConstraints = CA:FALSE
keyUsage = critical, digitalSignature, nonRepudiation, keyEncipherment
extendedKeyUsage = emailProtection, clientAuth
subjectAltName = email:demo@demo.pe
